### PR TITLE
Sort colocated waypoint lists; close various minor issues

### PR DESCRIPTION
**Pull request by yakra**
* Canonical Waypoint Names are deterministic now. I've not yet looked into how DIFFable graph files are.
* Deterministic **waypointsimplification.log**.
* **concurrencies.log:**
Deterministic concurrency detection portion. I've not yet addressed the per-traveler augments.
* ~**highwaydatastats.log:**
I didn't set out to make this deterministic, but 10 single-threaded trials & 10 multi-threaded trials have no DIFFs other than the initial `Travel Mapping highway mileage as of ...` line. OK! :)~

This allows me to simplify the code for my earlier modifications to the VISIBLE_HIDDEN_COLOC and HIDDEN_JUNCTION datachecks.

Takes 1.6-1.7 seconds on my machine. Will be a little faster on Noreaster.
I think DIFFs are worthwhile. :)

### CODE REVIEW

**Comment by yakra** [comment]
12f00bd9ef3378394dff9de74b8e7de10c345932 closes #133

**Comment by yakra** [comment]
ed5e912dd5b0f33a5c89e8cf677352246757faed closes #134

**Comment by yakra** [comment]
eccdb9b983447d54686d0179bd1c70224ef9c501 closes #140

**Comment by yakra** [comment]
d0cca48a2fd648a795490040eabb275ffe7e7a78 closes #142

**Comment by yakra** [comment]
> * **highwaydatastats.log:**
I didn't set out to make this deterministic, but 10 single-threaded trials & 10 multi-threaded trials have no DIFFs other than the initial `Travel Mapping highway mileage as of ...` line. OK! :)

That was the case for logs produced on noreaster. Not the case on my home machine. I've noticed differences in the way the FreeBSD and Ubuntu Python flavors iterate thru some container formats, such as dicts. I'll take a closer look at this later on.

**Comment by yakra** [comment]
6b2688c800ba0d8661f4aacc142335cb7a67888e closes #145

**Comment by yakra** [comment]
6c8512ab91dff5436b63ef470e18940047166192 closes #146

**Comment by yakra** [comment]
81d87af819c9270e69f0c2d9724631e04575e41f closes #149

**Comment by yakra** [comment]
I may have goofed in my fix for #134. Will look into this.

**Comment by jteresco** [comment]
Sorry I have not been following this one much.  Is it ready to merge in and be used in production going forward?

**Comment by yakra** [comment]
It is.

Currently testing out a datacheck for the OP in #57, which can be in a separate pull request.

**Pull request merged**
