### PR TITLE
graph construction cleanup

### PR DESCRIPTION
**Pull request by yakra**
`self.vertex1` & `self.vertex2` were already defined as `graph.vertices[s.waypoint1.unique_name]` & `graph.vertices[s.waypoint2.unique_name]`, making these lookups unnecessary. Saves about 0.4s during graph setup.

The `HighwayGraphCollapsedEdgeInfo` constructor is already done this way.

### CODE REVIEW

**Comment by yakra** [comment]
May have some more commits to add to this.

**Comment by yakra** [comment]
31c960223ccc1f0c033067ed885b5c41e85bf7b5:

We can visit each concurrrent HighwaySegment only once by checking whether it's the first segment in its concurrency list. Doing so removes the need to check a name for each to see if it's been visited, thus removing the need to store the `visited` & `segment_name` variables for each HighwaySegment. Thus we can remove 2 FOR loops (29 lines of code) and construct edge rights away, getting segment names from `HighwaySegment.segment_name()` during construction.

Calling the `HighwayGraphEdgeInfo` and initial `HighwayGraphCollapsedEdgeInfo` constructors have been combined into the same FOR loop.

**Comment by yakra** [comment]
Putting this on hold until I get https://github.com/yakra/DataProcessing/issues/64 sorted.

**Comment by yakra** [comment]
This one should be OK.

**Comment by jteresco** [comment]
I'm holding off on merging in any additional graph generation changes while I'm using the graphs heavily in class.  One more week of that then we'll have a break from all that and I'll be a little more adventurous.

**Comment by yakra** [comment]
Understandable. That graphs are used in your classes is a pretty important reason to make sure any changes are done right, and that things behave in an expected, predictable way.

**Pull request merged**
