### PR TITLE
traveled graph implementation (Python)

### PR DESCRIPTION
**Pull request by yakra**
Implements #196 in Python

### CODE REVIEW

**Comment by yakra** [comment]
* @jteresco, you only said "a new version number in the header"; I made the "2.0" assumption. Do you prefer a different number, or is 2.0 fine?
* Thoughts on adding "-collapsed" to TMG filenames, E.G. `AB-region-collapsed.tmg?` More descriptive / less ambiguous compared to a vanilla filename, and more convenient if I want to `mv *collapsed.tmg foo/`, or `rm *collapsed.tmg`, etc.
  - On the one hand, the links on the graph download page would be broken.
  - OTOH, it'll have to be revamped eventually.

**Comment by jteresco** [comment]
I like 2.0 and I like adding the format to every filename.  I can easily enough revamp the download page. I think HDX would be good, it would just start loading up the -collapsed graphs from the list in the DB.   More interesting will be to bring in user stats there for display and use in the algorithms.

**Comment by yakra** [comment]
OK. For now, the existing filenames are retained in this PR.

**Comment by yakra** [comment]
When revamping the graph download page, thoughts on including links to tmg2html "HDX-Lite" pages?
(Semi-related: #95)
*(I'd have to first update tmg2html to read `TMG 2.0 traveled` files. Relatively easy to do; just hinges on how #199 is resolved.)*

**Comment by jteresco** [comment]
Makes sense to me to link to HDX-Lite pages.  I think that whole page needs a little thought anyway now with 3 graph formats per subgraph.

**Comment by jteresco** [comment]
I am about 2 weeks away from what I hope is a chance to merge this in and make corresponding changes to get the new format graphs listed on the web site and to get the format documented for potential users.

**Comment by yakra** [comment]
> I am about 2 weeks away from what I hope is a chance to merge this in

Thanks, good to know.

> and make corresponding changes to get the new format graphs listed on the web site

Should I go ahead and make the change to `FOO-bar-collapsed.tmg` style filenames in anticipation of this, then?

> and to get the format documented for potential users.

Let's get #199 sorted before moving ahead. [Two questions], should I(https://github.com/TravelMapping/DataProcessing/issues/199#issuecomment-482184486):
* Use a single-`0` hex code for each edge in zero-traveler graphs? *(flagged as "Most likely do")*
* Add the number of travelers to the second header line? *(flagged as "To do or not to do?")*

**Comment by jteresco** [comment]
> > and make corresponding changes to get the new format graphs listed on the web site
> 
> Should I go ahead and make the change to `FOO-bar-collapsed.tmg` style filenames in anticipation of this, then?

Yes, let's go for it all in one shot.

> > and to get the format documented for potential users.
> 
> Let's get #199 sorted before moving ahead. [Two questions](https://github.com/TravelMapping/DataProcessing/issues/199#issuecomment-482184486), should I:
> 
>     * Use a single-`0` hex code for each edge in zero-traveler graphs? _(flagged as "Most likely do")_
> 
>     * Add the number of travelers to the second header line? _(flagged as "To do or not to do?")_

I think yes to both with an eye toward ease of parsing for potential users.

**Comment by yakra** [comment]
> Yes, let's go for it all in one shot.
...
I think yes to both with an eye toward ease of parsing for potential users.

All three changes are now live in this branch.

**Comment by yakra** [comment]
LOL, why not a benchmark.
BiggaTomato / UserData @ 207c8eb / HighwayData @ 0c0573b
Subgraph generation time increased from 99.9s to 159.3s.
No doubt most of that comes from hex code generation.

And nothing wrong with that, traveled graphs will be super neat to have. :)

**Comment by jteresco** [comment]
The time has come.  I'm bringing this in.  I'm going to try it out on my Mac and will make corresponding changes to the graph downloads page (https://github.com/TravelMapping/Web/issues/299) before putting to use for the production site updates on noreaster.

**Pull request merged**
