### PR TITLE
Quadtree: prevent infinite insert/refine recursion

### PR DESCRIPTION
**Pull request by yakra**
[aln.starrd.wpt](http://yakra.teresco.org/tests/Alanland/hwy_data/ALN/alngp/aln.starrd.wpt) was specifically designed to:
* look pretty in wptedit, and
* break the WaypointQuadtree insert/refine process.

Running it thru siteupdate.py, I get a ton of
```
  File "./siteupdate.py", line 72, in refine
    self.insert(p)
  File "./siteupdate.py", line 92, in insert
    self.ne_child.insert(w)
  File "./siteupdate.py", line 81, in insert
    self.refine()
```
scrolling off the top of my terminal window, until finally,
```
  File "./siteupdate.py", line 65, in refine
    self.nw_child = WaypointQuadtree(self.mid_lat,self.min_lng,self.max_lat,self.mid_lng)
RecursionError: maximum recursion depth exceeded

[0.3] Finding unprocessed wpt files.
```
followed by some more normal-looking output, then
```
[2.4] Performing data checks...Traceback (most recent call last):
  File "./siteupdate.py", line 2990, in <module>
    if r.point_list[0].is_hidden:
IndexError: list index out of range
```
I've modified the WaypointQuadtree so that each node can contain up to 50 unique locations, rather than 50 points.

### CODE REVIEW

**Comment by jteresco** [comment]
I like this.  Ready to merge and go to production?

**Comment by yakra** [comment]
I believe so.

**Just for fun:**
As of [HighwayData@a46d6d9](https://github.com/TravelMapping/HighwayData/tree/a46d6d9b7ca2f2f452f7e3ebe7123e109e51ced2),
Total number of Quadtree nodes: 62237 -> 42725
Number of bottom-level nodes, containing waypoints: 46678 -> 32044

**Comment by yakra** [comment]
@jteresco, does any info from/or about the quadtree get put into the DB, into the .sql file?
Anything to watch out for there?

**Comment by jteresco** [comment]
No, it's gone when the site update process ends.  Entirely to make searches by coordinates a lot more efficient.

**Pull request merged**
