### PR TITLE
datacheck enhancements

### PR DESCRIPTION
**Pull request by yakra**
See also: https://github.com/TravelMapping/Web/pull/378

### CODE REVIEW

**Comment by yakra** [comment]
Actually, I'm going to rethink this, depending on how the C++ version ends up getting implemented.

**Comment by yakra** [comment]
Closes #57
Closes https://github.com/yakra/DataProcessing/issues/49

C++ implementation done.
Reading waypoints for all routes from 18s -> 18.4s on BiggaTomato, single-threaded. That performance hit disappears once we're running 4 threads and the bottleneck is disk speed. :)

**Comment by jteresco** [comment]
Good to go live with this now?

**Comment by yakra** [comment]
Yes.

**Comment by jteresco** [comment]
OK, good.  It will be used on tonight's update.

**Pull request merged**
