### PR TITLE
COMBINE_CON_RTES (DataProcessing)

### LINKED ISSUE #492: Different ConnectedRoutes that can be combined
These will not always be flagged by the datachecks proposed in #338.
https://github.com/TravelMapping/DataProcessing/issues/338#issuecomment-1042097123
https://forum.travelmapping.net/index.php?topic=3652.msg19191#msg19191

Examples as of 0df0a8c1d1f5469a7b534ed899108c9101690acb:
[KY/IN: I-265FutLou](https://forum.travelmapping.net/index.php?topic=4823)
[ENG/SCT: B6318 & B6452](https://forum.travelmapping.net/index.php?topic=4824)
[DEU: A270 & B208](https://forum.travelmapping.net/index.php?topic=4825)
[ITA RA5 & RA6](https://forum.travelmapping.net/index.php?topic=2095.msg26969#msg26969)
[ESP: A15](https://forum.travelmapping.net/index.php?topic=4827)
[TKM/UZB: A381](https://forum.travelmapping.net/index.php?topic=4828)

FPs are possible, e.g. AB201.

Probably best to address #338 first, see what hash tables that produces, and get a better idea of how to proceed.

### PR DESCRIPTION
**Pull request by yakra**
Closes #492.

There will be a Web component to accompany this.

### CODE REVIEW

**Comment by jteresco** [comment]
Should I use this tonight?

**Comment by yakra** [comment]
Any thoughts on TravelMapping/Web#800?

**Comment by jteresco** [comment]
I think we can hold off until I can get you set up on a test server.

**Comment by yakra** [comment]
OK, sounds good.
In that case using this tonight sounds good.

You're off traveling now, right?
I might be able to set up a new server on one of my other lab machines. (Though I don't remember what I did back in 2019 and would have to mostly start from scratch again; may take a bit.)

Or stick bring lab2 back from the dead with a combination of its hardware and some other R420s I have.

Or -- *hardware?* -- plop its hard disk in an external adapter and boot lab6 up with it.
Yes. This may be my best bet for a quick solution?

**Comment by jteresco** [comment]
So if I give you write access on noreaster to /home/www/tmtest so you can put your Web files there, and we point it at the TravelMappingTest DB, which you should be able to populate with your version of the .sql file, would that test what you want?

**Comment by yakra** [comment]
Yeah, that'd work, thanks!
Not sure how I'd want to read into what db specifically; can I leave that to you?
the file is at `/home/yakra/ytm/DataProcessing/siteupdate/cplusplus/TravelMapping.sql`

(As an aside, if you're interested in seeing the latest bleeding edge cpp, go there and run `git diff`)

**Comment by jteresco** [comment]
You should have enough write access to put the version you want in `/home/www/tmtest`.

I can load up the DB when there's a file ready to go.

**Comment by yakra** [comment]
It's back.
(Ack, that took longer than I expected.)

**Comment by yakra** [comment]
just realized; is has no ranks table.
will see about appending

**Comment by yakra** [comment]
https://tmtest.teresco.org/devel/datacheck.php

**Comment by jteresco** [comment]
So ready for all this to go live tonight or is it better to work with it on tmtest for a bit first?  It's easy enough to load up the DB.

**Comment by yakra** [comment]
Thanks for dding the DB and write access!

Not ready just yet.
1. Bugfix in datacheck.php has not been [force pushed](https://github.com/TravelMapping/Web/pull/800#issuecomment-2423651125) yet.
2. Want to do some minor rewording on syserr.php
3. What will be in #800 at that point will be upstream from what you see at the datacheck link. I'll be ready to merge the stuff for the new datacheck, for this PR. Everything else (like that big brown table up top) is for hidden system support, which I'd like to hold off on pushing until the ITA split is ready to go. I believe it's in good shape; just wanna avoid any nasty last-minute surprises.
There will be a big merge conflict to resolve at that point. One I've resolved like 3 times now, so I have the hang of it. :D (Results are at the link.) It's not necessary to get the pull request through of course; I'd just like to do it first to stay organized.

**Comment by yakra** [comment]
New DB, same path: `/home/yakra/ytm/DataProcessing/siteupdate/cplusplus/TravelMapping.sql`
Just the changes concerning this PR this time.
Let me know when you have it in and I can scp the .php files over.

**Comment by yakra** [comment]
OK, I've checked out everything I want to for hidden systems.

For real this time:
> New DB, same path: `/home/yakra/ytm/DataProcessing/siteupdate/cplusplus/TravelMapping.sql`
Just the changes concerning this PR this time.
Let me know when you have it in and I can scp the .php files over.

**Comment by jteresco** [comment]
Reloaded the `TravelMappingTest` DB (sorry for the delay).

**Comment by yakra** [comment]
Looks good!

**Comment by yakra** [comment]
Since this isn't merged yet...
route_integrity.cpp does 7 different things. It kinda needs to be refactored.
Might do a force push. I'll let you know.

**Comment by yakra** [comment]
Good thing we held off on the merge.

Multi-threaded results are non-deterministic
```diff
7057d7056
< indka.ka010;KA/TG;;;COMBINE_CON_ROUTES;indtg.ka010@KA/TG
7823a7823
> indtg.ka010;KA/TG;;;COMBINE_CON_ROUTES;indka.ka010@KA/TG
```
due to comparison of Waypoint addresses:
https://github.com/TravelMapping/DataProcessing/blob/a93532fde68be0b03506e486f638814370df798e/siteupdate/cplusplus/classes/HighwaySystem/route_integrity.cpp#L118

**Solution:** drop the `w < p` condition and compare the region pointers instead. Better results AND more efficient.

**Comment by yakra** [comment]
Force pushed & ready to rock!

> route_integrity.cpp does 7 different things. It kinda needs to be refactored.

59% of it's gone compared to b046a77; 63% compared to a93532f.
Holding off on further refactoring until implementing hidden systems.
At that point it may even cease to exist as its own translation unit.

**Comment by yakra** [comment]
Let's hold off on this again while I ready about git internals

**Comment by yakra** [comment]
Reverted to the 1st force push (2 commits refactoring + 1 for the new feature) from the 2nd force push (1 commit squashing it all together).
For a minute there I was hung up on making 2 or 3 [blob](https://git-scm.com/book/en/v2/Git-Internals-Git-Objects) [objects](https://jvns.ca/blog/2023/09/14/in-a-git-repository--where-do-your-files-live-/) when I could be making 1, but meh, that's what [pack files](https://codewords.recurse.com/issues/three/unpacking-git-packfiles) are for.
Commits [are and are not](https://jvns.ca/blog/2024/01/05/do-we-think-of-git-commits-as-diffs--snapshots--or-histories/) diffs.
I'll err on the side of an understandable commit history, with discrete commits for discrete changes.

### Ready to rock.

**Comment by yakra** [comment]
Hold on, gonna mess around with translation units. :P

**Comment by yakra** [comment]
Noticed that 82b03c4 added a couple dependencies to ConnectedRoute.cpp, so I decided to break out ConnectedRoute/dataceck.cpp into its own file, including a smaller subset of the headers in each.
While this does mean greater *combined* compile time due to double-processing the shared headers, it's outweighed by more often only having to recompile only *one* of the files.
Of course, ConnectedRoute is small potatoes. The real time savings would be heavy-hitters like Waypoint.cpp. I may get to that in the future; low priority.

## Ready to rock!
*...That is what I honestly believe.*
Though of course, I do keep saying that. ;)
LOL quick, merge it in before I start tinkering around with whatever else!

---

dead branches:
* `46a47c4`, same as 6d2945f without the #include change in ConnectedRoute.h
* `d0f1894`, indentation before squash/rebase

**Comment by jteresco** [comment]
OK, finally a chance to bring this in.

**Comment by yakra** [comment]
Ha! Glad I got a chance to tweak it.
I don't think I've anything left to improve here, so no regrets! :)

**Pull request merged**
