### PR TITLE
C++ -N flag, #590

### PR DESCRIPTION
**Pull request by jteresco**

### CODE REVIEW

**Comment by yakra** [comment]
Just saw this. Off to work in a few mins; can give a closer look late evening.

**Comment by yakra** [comment]
...Or not! This all looks great; thanks for doing it.
No conflicts with anything I have in the pipeline, I believe.
Thankfully, `WaypointQuadtree::near_miss_waypoints` already has a `tolerance` argument, which makes life easier.

**Comment by yakra** [comment]
OH SHIT. Why did I merge this? Can we undo?
Hard reset & force push?

**Comment by michihdeu** [comment]
Should we mention the [parameters](https://github.com/TravelMapping/DataProcessing/blob/master/siteupdate/cplusplus/classes/Args/Args.cpp#L31) in the [readme](https://github.com/TravelMapping/DataProcessing/blob/master/README.md)? Maybe with an example?
Are they also available when running data check? If so, it would be nice to have the hint [here](https://github.com/TravelMapping/DataProcessing/blob/master/RUNNING.md).

**Comment by yakra** [comment]
Would also need the parameters added for site update.sh/datacheck

**Comment by yakra** [comment]
`//printf("Starting NmpSearchThread %02i\n", id); fflush(stdout);`
wasn't commemted back out, so there will be some text on screen and in siteupdate.log that we don't want.

for the sake of a clean commit history, can we do a quick hard reset & force push before others [update their forks](https://github.com/TravelMapping/DataProcessing/forks?include=active&page=1&period=2y&sort_by=last_updated)?

**Comment by jteresco** [comment]
> Can we undo? Hard reset & force push?

Go for it if you'd like.  I can take a look a little later otherwise.

**Comment by yakra** [comment]
Not 100% sure I have the access privileges to do that, via GitKraken at least. GitHub web interface may be another story. I can take a look in about 3 hours.

**Comment by yakra** [comment]
Now that I'm done kicking myself for being too hasty on the merge, I realize that editing & rebasing would give me credit (or "blame", as git calls it) for Jim's code, which is probably the greater evil here. Let's give Jim the cred he deserves for every other line in his commit.
I've made a new commit to master via the web interface.

**Comment by yakra** [comment]
I went ahead and deleted the `datadir` branch, @ 54fecf1e42a51cae358d12a5bf1f8b2cf4a0e935.
@jteresco, both `archivegraphs` & `commonupdate` are merged into master. OK to delete?

**Comment by jteresco** [comment]
Thanks!  And sounds good on deleting the stale branches.

**Pull request merged**
