### PR TITLE
move fatal error reporting before graph generation

### LINKED ISSUE #162: Failure in siteupdate.py reported much later
Recent changes have meant that when a data error slips in, the "ABORTING due to N errors" doesn't happen until after (the time consuming) generation of all the subgraphs.  I had gotten used to being able to ignore the site update process once graph generation started.  I'd like to see about getting that ABORTING condition moved back earlier so I have a better chance to notice the problem.  I just about was calling it a night when I noticed tonight's update had failed.  I'll try to check this out soon but wouldn't be sad if @yakra beat me to it.

### PR DESCRIPTION
**Pull request by yakra**
This closes #162.

Looks like we never had a `file.close()` for datacheckfps.csv.
I didn't add one, Shall we do so?

### CODE REVIEW

**Comment by jteresco** [comment]
> Looks like we never had a `file.close()` for datacheckfps.csv.
> I didn't add one, Shall we do so?

Yes, please do.

**Comment by yakra** [comment]
This is the case for updates.csv, systemupdates.csv, areagraphs.csv, systemgraphs.csv, multisystem.csv, multiregion.csv, datacheckfps.csv.
Shall I add `file.close()` for all of these?

**Comment by jteresco** [comment]
Yes, I think that would be good.  It's not really hurting anything but it's good practice.

**Comment by yakra** [comment]
Done.

**Comment by jteresco** [comment]
Excellent, thanks.  Merging.

**Pull request merged**
